### ISSUE TITLE
SSL Certificate Error for jacobjordan.tech

### ISSUE THREAD

**Issue by abetusk** [wuspy/asteroids#1]
My apologies that this is not the proper place to raise this issue but I thought you would want to know.

When trying to access `https://jacobjordan.tech/` I get an `Invalid SSL certificate` (code 526) from cloudfare.com. When trying to access `http://jacobjordan.tech/` it redirects to the `https` site.

**Comment by wuspy** [comment]
Thank you!! Should be fixed now.
